import {Eye, Filter, RotateCcw, Smile, UserSearch} from 'lucide-react-native';

const data = [
  {
    title: 'VIP',
    body: 'VIP Bulan Terbatas',
    imgUrl: 'https://i.pravatar.cc/1000?img=10',
    bgColor: '#D1B378',
    bgKartu: '#906F2E',
    textBg: '#FFFFFF',
    bgKeuntungan: '#B347B5',
    bgKeuntungan2: '#B347B5',
    bgKeuntungan3: '#B347B5',
    judulKeuntungan1: 'Suka Tak Terbatas',
    bodyKeuntungan1: 'Suka sebanyak yang kamu mau',
    icon1: Smile,
    judulKeuntungan2: 'Gratis 5 Super Per hari',
    bodyKeuntungan2: 'Percocokan melonjak 5 kali!',
    icon2: UserSearch,
    judulKeuntungan3: 'Berbalik Tak Terbatas',
    bodyKeuntungan3: 'Kembali dan geser lagi!',
    icon3: RotateCcw,
    total: 'Rp 459.000 Dapatkan Premium',
  },
  {
    title: 'GOLD',
    body: 'Hak istimewa tidak valid',
    imgUrl: 'https://i.pravatar.cc/1000?img=10',
    bgColor: '#684105',
    bgKartu: '#684105',
    textBg: '#FFFFFF',
    bgKeuntungan: '#B347B5',
    judulKeuntungan1: 'Lihat Siapa Suka Saya',
    bodyKeuntungan1: '159 orang menyukai Anda',
    icon1: Smile,
    total: 'Rp 159.000 Beli Sekarang',
  },
  {
    title: 'PREMIUM',
    body: 'Keuntungan Premium',
    imgUrl: 'https://i.pravatar.cc/1000?img=10',
    bgColor: '#959494',
    bgKartu: '#959494',
    textBg: '#FFFFFF',
    bgKeuntungan: '#B347B5',
    bgKeuntungan2: '#B347B5',
    judulKeuntungan1: 'Siapa Mengunjungi Saya',
    bodyKeuntungan1: 'Lihat siapa yang mengunjungi profill',
    icon1: Eye,
    judulKeuntungan2: 'Saringan Lanjutkan',
    bodyKeuntungan2: 'Aktifkan untuk melihat hanya pengguna',
    icon2: Filter,
    total: 'Rp 459.000 Dapatkan Premium',
  },
];

export default data;
